# Generated by Django 4.1.4 on 2023-06-28 18:45

import core.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
        ),
        migrations.CreateModel(
            name='Apresentacao',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base')),
                ('titulo', models.CharField(max_length=100)),
                ('icon', stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={}, verbose_name='icon')),
                ('iamgem_fundo', stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={}, verbose_name='icon')),
                ('instagram', models.CharField(max_length=100)),
                ('instagram_link', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Apresentacao',
                'verbose_name_plural': 'Apresentacao',
            },
            bases=('core.base',),
        ),
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base')),
                ('titulo', models.CharField(max_length=100)),
                ('textos', models.TextField()),
            ],
            bases=('core.base',),
        ),
    ]
