# Generated by Django 4.1.4 on 2023-06-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sobre',
            options={'verbose_name': 'Sobre', 'verbose_name_plural': 'Sobre'},
        ),
    ]
