# Generated by Django 4.1.4 on 2023-06-28 20:32

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contato_cores_detalhes_duvidas_duvidasrespostas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apresentacao',
            name='iamgem_fundo',
            field=stdimage.models.StdImageField(force_min_size=False, help_text='Imagem de fundo da tela inicial', upload_to=core.models.get_file_path, variations={}, verbose_name='fundo'),
        ),
        migrations.AlterField(
            model_name='apresentacao',
            name='icon',
            field=stdimage.models.StdImageField(force_min_size=False, help_text='Icone da página', upload_to=core.models.get_file_path, variations={}, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='apresentacao',
            name='instagram',
            field=models.CharField(help_text='Usuario do seu instagram', max_length=100),
        ),
        migrations.AlterField(
            model_name='apresentacao',
            name='instagram_link',
            field=models.CharField(help_text='Link do seu instagram', max_length=100),
        ),
    ]
