# Generated by Django 3.2 on 2023-06-29 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_apresentacao_iamgem_fundo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cores',
            old_name='cor_contact_background',
            new_name='cor_contact_fundo',
        ),
        migrations.RenameField(
            model_name='cores',
            old_name='cor_contact_h1',
            new_name='cor_contact_texto',
        ),
        migrations.RenameField(
            model_name='cores',
            old_name='cor_contact_p',
            new_name='cor_contact_titulo',
        ),
        migrations.RenameField(
            model_name='cores',
            old_name='cor_details_background',
            new_name='cor_imagem_fundo',
        ),
        migrations.RenameField(
            model_name='cores',
            old_name='cor_details_p',
            new_name='cor_imagem_titulo',
        ),
        migrations.RenameField(
            model_name='cores',
            old_name='cor_details_titulo',
            new_name='cor_price_fundo',
        ),
        migrations.RenameField(
            model_name='cores',
            old_name='cor_imagem_background',
            new_name='cor_price_texto',
        ),
        migrations.RenameField(
            model_name='cores',
            old_name='cor_imagem_h1',
            new_name='cor_price_titulo',
        ),
        migrations.RenameField(
            model_name='cores',
            old_name='cor_price_background',
            new_name='cor_question_fundo',
        ),
        migrations.RenameField(
            model_name='cores',
            old_name='cor_price_h1',
            new_name='cor_question_texto',
        ),
        migrations.RenameField(
            model_name='cores',
            old_name='cor_price_p',
            new_name='cor_question_titulo',
        ),
        migrations.RenameField(
            model_name='cores',
            old_name='cor_question_background',
            new_name='cor_sobre_fundo',
        ),
        migrations.RenameField(
            model_name='cores',
            old_name='cor_question_h1',
            new_name='cor_sobre_titulo',
        ),
        migrations.RemoveField(
            model_name='cores',
            name='cor_question_p',
        ),
        migrations.RemoveField(
            model_name='cores',
            name='cor_sobre_background',
        ),
        migrations.RemoveField(
            model_name='cores',
            name='cor_sobre_h1',
        ),
        migrations.AddField(
            model_name='precos',
            name='cor_fundo',
            field=models.CharField(default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Insira uma cor válida no formato hexadecimal, começando com #.', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='precos',
            name='cor_texto',
            field=models.CharField(default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Insira uma cor válida no formato hexadecimal, começando com #.', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='precos',
            name='cor_titulo',
            field=models.CharField(default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Insira uma cor válida no formato hexadecimal, começando com #.', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
    ]
