# Generated by Django 3.2 on 2023-06-29 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230629_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='precosplano1dados',
            options={'verbose_name': 'Detalhes Preço plano 1', 'verbose_name_plural': 'Detalhes Preço plano 1'},
        ),
        migrations.AlterModelOptions(
            name='precosplano2',
            options={'verbose_name': 'Preço plano 2', 'verbose_name_plural': 'Preço plano 2'},
        ),
        migrations.AlterModelOptions(
            name='precosplano2dados',
            options={'verbose_name': 'Detalhes Preço plano 2', 'verbose_name_plural': 'Detalhes Preço plano 2'},
        ),
        migrations.RemoveField(
            model_name='precos',
            name='cor_fundo',
        ),
        migrations.RemoveField(
            model_name='precos',
            name='cor_texto',
        ),
        migrations.RemoveField(
            model_name='precos',
            name='cor_titulo',
        ),
        migrations.AddField(
            model_name='detalhes',
            name='cor_fundo',
            field=models.CharField(default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Insira uma cor válida no formato hexadecimal, começando com #.', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='detalhes',
            name='cor_texto',
            field=models.CharField(default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Insira uma cor válida no formato hexadecimal, começando com #.', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='detalhes',
            name='cor_titulo',
            field=models.CharField(default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Insira uma cor válida no formato hexadecimal, começando com #.', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
    ]
