# Generated by Django 3.2 on 2023-06-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_iamgem_fundo_apresentacao_imagem_back'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalhes',
            old_name='iamgem',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='imagenslista',
            old_name='iamgem',
            new_name='img',
        ),
    ]
