# Generated by Django 3.2 on 2023-06-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230630_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='precosplano1dados',
            options={'verbose_name': 'Preço plano 1 texto', 'verbose_name_plural': 'Preço plano 1 texto'},
        ),
        migrations.AlterModelOptions(
            name='precosplano2dados',
            options={'verbose_name': 'Preço plano 2 texto', 'verbose_name_plural': 'Preço plano 2 texto'},
        ),
        migrations.AlterField(
            model_name='precosplano1dados',
            name='destaque',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='precosplano2dados',
            name='destaque',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
