# Generated by Django 3.2 on 2023-06-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230630_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precosplano1dados',
            name='destaque',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='precosplano1dados',
            name='texto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='precosplano2dados',
            name='destaque',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='precosplano2dados',
            name='texto',
            field=models.TextField(),
        ),
    ]
