# Generated by Django 3.2 on 2023-06-30 21:24

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230630_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='precosplano1',
            name='img',
            field=stdimage.models.StdImageField(default='', force_min_size=False, upload_to=core.models.get_file_path, variations={}, verbose_name='imagem'),
        ),
        migrations.AddField(
            model_name='precosplano2',
            name='img',
            field=stdimage.models.StdImageField(default='', force_min_size=False, upload_to=core.models.get_file_path, variations={}, verbose_name='imagem'),
        ),
    ]
