# Generated by Django 3.2 on 2023-06-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230630_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duvidasrespostas',
            name='resposta',
            field=models.TextField(),
        ),
    ]
